#ifndef _TERMINAL_COLORS_H
#define _TERMINAL_COLORS_H
#define ANSI_RESET      "\x1b[0m"
#define ANSI_BOLD       "\x1b[1m"
#define ANSI_DARK       "\x1b[2m"
#define ANSI_UNDERLINE  "\x1b[4m"
#define ANSI_BLINK      "\x1b[5m"
#define ANSI_REVERSE    "\x1b[7m"
#define ANSI_CONCEALED  "\x1b[8m"
#define ANSI_GRAY       "\x1b[30m"
#define ANSI_GREY       "\x1b[30m"
#define ANSI_RED        "\x1b[31m"
#define ANSI_GREEN      "\x1b[32m"
#define ANSI_YELLOW     "\x1b[33m"
#define ANSI_BLUE       "\x1b[34m"
#define ANSI_MAGENTA    "\x1b[35m"
#define ANSI_CYAN       "\x1b[36m"
#define ANSI_WHITE      "\x1b[37m"
#define ANSI_BG_GRAY    "\x1b[40m"
#define ANSI_BG_GREY    "\x1b[40m"
#define ANSI_BG_RED     "\x1b[41m"
#define ANSI_BG_GREEN   "\x1b[42m"
#define ANSI_BG_YELLOW  "\x1b[43m"
#define ANSI_BG_BLUE    "\x1b[44m"
#define ANSI_BG_MAGENTA "\x1b[45m"
#define ANSI_BG_CYAN    "\x1b[46m"
#define ANSI_BG_WHITE   "\x1b[47m"
#endif //_TERMINAL_COLORS_H